PROMPT:
  - KEY: "JIRA-TASK"
    LABEL: "Jira task ID"
    DEFAULT_VALUE: "{{BRANCH_NAME}}"
  - KEY: "CHANGE"
    LABEL: "Type of change"
    OPTIONS:
      - VALUE: "feature"
        DESC: "Add new feature"
      - VALUE: "fix"
        DESC: "A bug fix"
      - VALUE: "test"
        DESC: "Adding missing tests or correcting ones"
      - VALUE: "style"
        DESC: "A code change to improve clean code"
      - VALUE: "build-ci"
        DESC: "Changes on the build system or CI files"
      - VALUE: "refactor"
        DESC: "A code change"
      - VALUE: "docs"
        DESC: "Documentation only changes"
  - KEY: "MESSAGE"
    LABEL: "Commit message"
  - KEY: "LABEL"
    LABEL: "Label"
    OPTIONS:
      - VALUE: ""
        DESC: "No label"
      - VALUE: "[CI SKIP]"
        DESC: "Skip continous integration pipeline"
      - VALUE: "[WIP]"
        DESC: "Work In Progress"
TEMPLATE: "{{JIRA-TASK}} ({{CHANGE}}): {{MESSAGE}}{{LABEL}}"
